// <auto-generated />
using KashiHomeFood.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KashiHomeFood.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20180429211405_Menu db added")]
    partial class Menudbadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KashiHomeFood.Models.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("ID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("KashiHomeFood.Models.FoodMenu", b =>
                {
                    b.Property<int>("FoodID");

                    b.Property<int>("MenuID");

                    b.HasKey("FoodID", "MenuID");

                    b.HasIndex("MenuID");

                    b.ToTable("FoodMenus");
                });

            modelBuilder.Entity("KashiHomeFood.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("KashiHomeFood.Models.FoodMenu", b =>
                {
                    b.HasOne("KashiHomeFood.Models.Food", "Food")
                        .WithMany("FoodMenus")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KashiHomeFood.Models.Menu", "Menu")
                        .WithMany("FoodMenus")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
